name: hello

on:
  workflow_dispatch:
    inputs:
      environment:
        description: " hello enter your  wrok flow "   
        default: 'dev'
        required: true 
        type: choice 
        options :
          - dev
          - pod
          - staging

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: to greet the users
        run: echo "hello welcome to my repo"

      - name: checkout the code using actions
        uses: actions/checkout@v4

      - name: hello from GitHub Actions
        run: echo "hello $USER from GitHub Actions"
