name: hello
on: 
  workflow_dispatch: 
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: say hello to me 
      run: echo "hello jana "
          
    - name: hello to username
      run: echo " hello " 
