name : sam 
on: push
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: sample works flow hands on 
        run: echo " hello bhaiya "
      - name: check the versions 
        run: echo "$(python --version)"
      - name: Check installed tools
        run: |
          docker --version
          python3 --version
          node --version
          git --version
