name: PR

on: 
  workflow_dispatch:
  


jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Print PR branch name
        run: 'echo "PR check running for branch: ${{ github.head_ref }}"'
