name: sec

on:
  workflow_dispatch:

jobs:
  sec-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check the secret variable
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi

  sec-check2:
    runs-on: ubuntu-latest

    steps:
      - name: Try to print the secret
        run: |
          echo "${{ secrets.MY_SECRET_MESSAGE }}"
