name: Parallel Jobs Demo

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Run lint
        run: echo "Linting code..."

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: echo "Running tests..."

  summary:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Print branch type
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "This is a main branch push"
          else
            echo "This is a feature branch push"
          fi

      - name: Print commit message
        run: echo " Commit Message:${{ github.event.head_commit.message }}"