name: try
on:
  workflow_dispatch:
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: say hello to me 
      run: echo "hello"

    - name: hello to the user 
      run: echo "hi $USER "
  code:
    runs-on: ubuntu-latest
    steps:
      - name: build the code 
        run: |
              sudo apt get update 
              sudo apt install docker.io -y
              docker --version 

  build:
        needs: [ code ]
        runs-on: ubuntu-latest
        steps:
          - name: create docker images 
            run: |
                  docker pull nginx 
                  docker images 

  test:
       needs: build
       runs-on: ubuntu-latest
       steps:
         - name: sample
           run: echo "done "
         
      
  
        
   
